// Code generated by Slice Machine. DO NOT EDIT.

import HomeHero from './HomeHero';
import SellingPoints from './SellingPoints';
import TutorCarousel from './TutorCarousel';

export {
	HomeHero,
	SellingPoints,
	TutorCarousel,
};

export const components = {
	home_hero: HomeHero,
	selling_points: SellingPoints,
	tutor_carousel: TutorCarousel,
};
