// Code generated by Slice Machine. DO NOT EDIT.

import CourseClasses from './CourseClasses';
import CourseTutors from './CourseTutors';
import Resource from './Resource';

export {
	CourseClasses,
	CourseTutors,
	Resource,
};

export const components = {
	course_classes: CourseClasses,
	course_tutors: CourseTutors,
	resource: Resource,
};
