// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact';
import Content from './Content';
import Hero from './Hero';
import Pricing from './Pricing';
import Results from './Results';
import Reviews from './Reviews';
import Timeline from './Timeline';
import TutorCarousel from './TutorCarousel';

export {
	Contact,
	Content,
	Hero,
	Pricing,
	Results,
	Reviews,
	Timeline,
	TutorCarousel,
};

export const components = {
	contact: Contact,
	content: Content,
	hero: Hero,
	pricing: Pricing,
	results: Results,
	reviews: Reviews,
	timeline: Timeline,
	tutor_carousel: TutorCarousel,
};
