// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import Hero from './Hero';
import Pricing from './Pricing';
import Results from './Results';
import Reviews from './Reviews';
import TutorCarousel from './TutorCarousel';

export {
	Content,
	Hero,
	Pricing,
	Results,
	Reviews,
	TutorCarousel,
};

export const components = {
	content: Content,
	hero: Hero,
	pricing: Pricing,
	results: Results,
	reviews: Reviews,
	tutor_carousel: TutorCarousel,
};
