// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import SellingPoints from './SellingPoints';
import TutorCarousel from './TutorCarousel';

export {
	Hero,
	SellingPoints,
	TutorCarousel,
};

export const components = {
	hero: Hero,
	selling_points: SellingPoints,
	tutor_carousel: TutorCarousel,
};
